// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-WiFi

#include "ui.h"

void scanButton_callback(lv_event_t * e)
{
	// Your code here
}

void connectButton_callback(lv_event_t * e)
{
	// Your code here
}

void toggle_password_mode(lv_event_t * e)
{
	// Your code here
}
