// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-temp-humi

#include "ui.h"

void ui_comp_Light_Switch_create_hook(lv_obj_t * comp)
{
}
