// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-temp-humi

#ifndef _UI_COMP_LIGHT_SWITCH_H
#define _UI_COMP_LIGHT_SWITCH_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Light_Switch
#define UI_COMP_LIGHT_SWITCH_LIGHT_SWITCH 0
#define _UI_COMP_LIGHT_SWITCH_NUM 1
lv_obj_t * ui_Light_Switch_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
