// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-temp-humi

#ifndef _RESPEAKER_DASHBOARD_TEMP_HUMI_UI_COMP_HOOK_H
#define _RESPEAKER_DASHBOARD_TEMP_HUMI_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Light_Switch_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
