// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-temp-humi

#include "ui.h"

// COMPONENT Light_Switch

lv_obj_t * ui_Light_Switch_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Light_Switch;
    cui_Light_Switch = lv_switch_create(comp_parent);
    lv_obj_set_width(cui_Light_Switch, 60);
    lv_obj_set_height(cui_Light_Switch, 30);
    lv_obj_set_x(cui_Light_Switch, 27);
    lv_obj_set_y(cui_Light_Switch, 12);
    lv_obj_set_align(cui_Light_Switch, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LIGHT_SWITCH_NUM);
    children[UI_COMP_LIGHT_SWITCH_LIGHT_SWITCH] = cui_Light_Switch;
    lv_obj_add_event_cb(cui_Light_Switch, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Light_Switch, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Light_Switch_create_hook(cui_Light_Switch);
    return cui_Light_Switch;
}

