// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-temp-humi

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel2;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_time;
extern lv_obj_t * uic_day;
extern lv_obj_t * uic_date;
extern lv_obj_t * uic_LightSwitch;
extern lv_obj_t * uic_FanSwitch;
extern lv_obj_t * uic_TvSwitch;
extern lv_obj_t * uic_AcSwitch;
extern lv_obj_t * uic_ControllerLabel;
extern lv_obj_t * uic_ControllerIndicator;
extern lv_obj_t * uic_tempArc;
extern lv_obj_t * uic_temp;
extern lv_obj_t * uic_humiArc;
extern lv_obj_t * uic_humi;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

