// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-WiFi

#ifndef UI_WIFISETUP_H
#define UI_WIFISETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WiFiSetup
extern void ui_WiFiSetup_screen_init(void);
extern void ui_WiFiSetup_screen_destroy(void);
extern void ui_event_WiFiSetup(lv_event_t * e);
extern lv_obj_t * ui_WiFiSetup;
extern lv_obj_t * ui_TitleLabel;
extern lv_obj_t * ui_NetworkLabel;
extern void ui_event_ScanButton(lv_event_t * e);
extern lv_obj_t * ui_ScanButton;
extern lv_obj_t * ui_ScanLabel;
extern lv_obj_t * ui_NetworkDropdown;
extern void ui_event_PasswordTextArea(lv_event_t * e);
extern lv_obj_t * ui_PasswordTextArea;
extern void ui_event_PasswordKeyboard(lv_event_t * e);
extern lv_obj_t * ui_PasswordKeyboard;
extern void ui_event_ConnectButton(lv_event_t * e);
extern lv_obj_t * ui_ConnectButton;
extern lv_obj_t * ui_ConnectLabel;
extern lv_obj_t * ui_StatusLabel;
extern void ui_event_ShowPasswordButton(lv_event_t * e);
extern lv_obj_t * ui_ShowPasswordButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

