// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-WiFi

#include "ui.h"

lv_obj_t * ui_WiFiSetup = NULL;
lv_obj_t * ui_TitleLabel = NULL;
lv_obj_t * ui_NetworkLabel = NULL;
lv_obj_t * ui_ScanButton = NULL;
lv_obj_t * ui_ScanLabel = NULL;
lv_obj_t * ui_NetworkDropdown = NULL;
lv_obj_t * ui_PasswordTextArea = NULL;
lv_obj_t * ui_PasswordKeyboard = NULL;
lv_obj_t * ui_ConnectButton = NULL;
lv_obj_t * ui_ConnectLabel = NULL;
lv_obj_t * ui_StatusLabel = NULL;
lv_obj_t * ui_ShowPasswordButton = NULL;
// event funtions
void ui_event_WiFiSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScanButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scanButton_callback(e);
    }
}

void ui_event_PasswordTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_PasswordKeyboard,  ui_PasswordTextArea);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_PasswordKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connectButton_callback(e);
    }
}

void ui_event_ShowPasswordButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        toggle_password_mode(e);
    }
}

// build funtions

void ui_WiFiSetup_screen_init(void)
{
    ui_WiFiSetup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFiSetup, lv_color_hex(0x1D4D78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_WiFiSetup, lv_color_hex(0x001F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_WiFiSetup, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleLabel = lv_label_create(ui_WiFiSetup);
    lv_obj_set_width(ui_TitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleLabel, -270);
    lv_obj_set_y(ui_TitleLabel, 13);
    lv_obj_set_align(ui_TitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TitleLabel, "Wi-Fi Setup");
    lv_obj_set_style_text_color(ui_TitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkLabel = lv_label_create(ui_WiFiSetup);
    lv_obj_set_width(ui_NetworkLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworkLabel, -263);
    lv_obj_set_y(ui_NetworkLabel, 65);
    lv_obj_set_align(ui_NetworkLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_NetworkLabel, "Select Your Wi-Fi Network");
    lv_obj_set_style_text_color(ui_NetworkLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworkLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworkLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScanButton = lv_btn_create(ui_WiFiSetup);
    lv_obj_set_width(ui_ScanButton, 100);
    lv_obj_set_height(ui_ScanButton, 50);
    lv_obj_set_x(ui_ScanButton, -10);
    lv_obj_set_y(ui_ScanButton, -189);
    lv_obj_set_align(ui_ScanButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScanButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScanButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScanButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScanButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScanButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ScanButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_ScanButton, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_ScanButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_ScanButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_ScanButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_ScanButton, 200, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_ScanButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_ScanButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ScanLabel = lv_label_create(ui_ScanButton);
    lv_obj_set_width(ui_ScanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScanLabel, "SCAN");

    ui_NetworkDropdown = lv_dropdown_create(ui_WiFiSetup);
    lv_obj_set_width(ui_NetworkDropdown, 334);
    lv_obj_set_height(ui_NetworkDropdown, 50);
    lv_obj_set_x(ui_NetworkDropdown, -208);
    lv_obj_set_y(ui_NetworkDropdown, 111);
    lv_obj_set_align(ui_NetworkDropdown, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_NetworkDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PasswordTextArea = lv_textarea_create(ui_WiFiSetup);
    lv_obj_set_width(ui_PasswordTextArea, 369);
    lv_obj_set_height(ui_PasswordTextArea, 52);
    lv_obj_set_x(ui_PasswordTextArea, 185);
    lv_obj_set_y(ui_PasswordTextArea, -105);
    lv_obj_set_align(ui_PasswordTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordTextArea, "Enter Wi-Fi Password");
    lv_textarea_set_password_mode(ui_PasswordTextArea, true);

    ui_PasswordKeyboard = lv_keyboard_create(ui_WiFiSetup);
    lv_obj_set_width(ui_PasswordKeyboard, 515);
    lv_obj_set_height(ui_PasswordKeyboard, 232);
    lv_obj_set_x(ui_PasswordKeyboard, 111);
    lv_obj_set_y(ui_PasswordKeyboard, 69);
    lv_obj_set_align(ui_PasswordKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ConnectButton = lv_btn_create(ui_WiFiSetup);
    lv_obj_set_width(ui_ConnectButton, 149);
    lv_obj_set_height(ui_ConnectButton, 50);
    lv_obj_set_x(ui_ConnectButton, -294);
    lv_obj_set_y(ui_ConnectButton, 125);
    lv_obj_set_align(ui_ConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ConnectButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConnectButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ConnectButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_ConnectButton, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_ConnectButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_ConnectButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_ConnectButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_ConnectButton, 200, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_ConnectButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_ConnectButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ConnectLabel = lv_label_create(ui_ConnectButton);
    lv_obj_set_width(ui_ConnectLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConnectLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectLabel, "CONNECT & SAVE");

    ui_StatusLabel = lv_label_create(ui_WiFiSetup);
    lv_obj_set_width(ui_StatusLabel, 500);
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabel, -114);
    lv_obj_set_y(ui_StatusLabel, 184);
    lv_obj_set_align(ui_StatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatusLabel, "Status : Ready");
    lv_obj_set_style_text_color(ui_StatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShowPasswordButton = lv_btn_create(ui_WiFiSetup);
    lv_obj_set_width(ui_ShowPasswordButton, 50);
    lv_obj_set_height(ui_ShowPasswordButton, 50);
    lv_obj_set_x(ui_ShowPasswordButton, 346);
    lv_obj_set_y(ui_ShowPasswordButton, -105);
    lv_obj_set_align(ui_ShowPasswordButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShowPasswordButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShowPasswordButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ShowPasswordButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShowPasswordButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShowPasswordButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ShowPasswordButton, &ui_img_visible_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ShowPasswordButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ShowPasswordButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ShowPasswordButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ShowPasswordButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ShowPasswordButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ShowPasswordButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ShowPasswordButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShowPasswordButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ShowPasswordButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_ShowPasswordButton, &ui_img_1107427757, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_ShowPasswordButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_ShowPasswordButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_ScanButton, ui_event_ScanButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordTextArea, ui_event_PasswordTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordKeyboard, ui_event_PasswordKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConnectButton, ui_event_ConnectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShowPasswordButton, ui_event_ShowPasswordButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiSetup, ui_event_WiFiSetup, LV_EVENT_ALL, NULL);

}

void ui_WiFiSetup_screen_destroy(void)
{
    if(ui_WiFiSetup) lv_obj_del(ui_WiFiSetup);

    // NULL screen variables
    ui_WiFiSetup = NULL;
    ui_TitleLabel = NULL;
    ui_NetworkLabel = NULL;
    ui_ScanButton = NULL;
    ui_ScanLabel = NULL;
    ui_NetworkDropdown = NULL;
    ui_PasswordTextArea = NULL;
    ui_PasswordKeyboard = NULL;
    ui_ConnectButton = NULL;
    ui_ConnectLabel = NULL;
    ui_StatusLabel = NULL;
    ui_ShowPasswordButton = NULL;

}
