// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-temp-humi

#ifndef _RESPEAKER_DASHBOARD_TEMP_HUMI_UI_H
#define _RESPEAKER_DASHBOARD_TEMP_HUMI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * rotateFan_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_441248079);    // assets/smart-house.png
LV_IMG_DECLARE(ui_img_bulb_png);    // assets/bulb.png
LV_IMG_DECLARE(ui_img_fan_png);    // assets/fan.png
LV_IMG_DECLARE(ui_img_1309870313);    // assets/tv-app.png
LV_IMG_DECLARE(ui_img_1202935209);    // assets/air-conditioning.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_616381548);    // assets/m2e-logo-ReSpeaker.png
LV_IMG_DECLARE(ui_img_1561736797);    // assets/temp-w.png
LV_IMG_DECLARE(ui_img_281639832);    // assets/humidity-w.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
