// This file was generated by SquareLine Studio
// SquareLine Studio version: 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-WiFi

#include "ui.h"
#include "home_control.h"
#include "lvgl_port.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#define WIFI_SCAN_MAX_NETWORKS 20

typedef struct {
    char ssid[33];
    char password[65];
} wifi_connect_params_t;

static void wifi_scan_task(void *arg)
{
    home_wifi_network_t networks[WIFI_SCAN_MAX_NETWORKS];
    uint16_t count = WIFI_SCAN_MAX_NETWORKS;

    bool success = home_wifi_scan(networks, &count);

    if (lvgl_port_lock(-1)) {

        if (!success) {

            lv_label_set_text(
                ui_StatusLabel,
                "Wi-Fi scan failed");

        } else if (count == 0) {

            lv_dropdown_clear_options(ui_NetworkDropdown);

            lv_label_set_text(
                ui_StatusLabel,
                "No Wi-Fi networks found");

        } else {

            static char options[
                WIFI_SCAN_MAX_NETWORKS * 34
            ];

            options[0] = '\0';

            for (uint16_t i = 0;
                 i < count;
                 i++) {

                if (i > 0) {
                    strncat(
                        options,
                        "\n",
                        sizeof(options) - strlen(options) - 1);
                }

                strncat(
                    options,
                    networks[i].ssid,
                    sizeof(options) - strlen(options) - 1);
            }

            lv_dropdown_set_options(
                ui_NetworkDropdown,
                options);

            lv_dropdown_set_selected(
                ui_NetworkDropdown,
                0);

            char status[64];

            snprintf(
                status,
                sizeof(status),
                "%u network%s found",
                (unsigned)count,
                count == 1 ? "" : "s");

            lv_label_set_text(
                ui_StatusLabel,
                status);
        }

        lvgl_port_unlock();
    }

    vTaskDelete(NULL);
}

static void wifi_connect_task(void *arg)
{
    wifi_connect_params_t *params =
        (wifi_connect_params_t *)arg;

    bool success =
        home_wifi_connect_and_save(
            params->ssid,
            params->password);

    free(params);

    if (lvgl_port_lock(-1)) {

        if (success) {

            lv_label_set_text(
                ui_StatusLabel,
                "Connected! Saving settings...");

            lvgl_port_unlock();

            vTaskDelay(pdMS_TO_TICKS(1800));

            if (lvgl_port_lock(-1)) {
                lv_disp_load_scr(ui_Screen1);
                lvgl_port_unlock();
            }

            vTaskDelete(NULL);
            return;

        } else {
            lv_label_set_text(
                ui_StatusLabel,
                "Connection failed. Check password.");
        }

        lvgl_port_unlock();
    }

    vTaskDelete(NULL);
}

void scanButton_callback(lv_event_t * e)
{
    (void)e;

    if (lvgl_port_lock(-1)) {

        lv_label_set_text(
            ui_StatusLabel,
            "Scanning for Wi-Fi networks...");

        lvgl_port_unlock();
    }

    xTaskCreate(
        wifi_scan_task,
        "wifi_scan",
        4096,
        NULL,
        5,
        NULL);
}

void connectButton_callback(lv_event_t * e)
{
    (void)e;

    wifi_connect_params_t *params =
        calloc(1, sizeof(wifi_connect_params_t));

    if (params == NULL) {

        if (lvgl_port_lock(-1)) {
            lv_label_set_text(
                ui_StatusLabel,
                "Out of memory");
            lvgl_port_unlock();
        }

        return;
    }

    if (lvgl_port_lock(-1)) {

        lv_dropdown_get_selected_str(
            ui_NetworkDropdown,
            params->ssid,
            sizeof(params->ssid));

        const char *password =
            lv_textarea_get_text(ui_PasswordTextArea);

        strncpy(
            params->password,
            password ? password : "",
            sizeof(params->password) - 1);

        params->password[
            sizeof(params->password) - 1] = '\0';

        lv_label_set_text(
            ui_StatusLabel,
            "Connecting to Wi-Fi...");

        lvgl_port_unlock();

    } else {

        free(params);
        return;
    }

    if (params->ssid[0] == '\0') {

        free(params);

        if (lvgl_port_lock(-1)) {
            lv_label_set_text(
                ui_StatusLabel,
                "Please select a Wi-Fi network");
            lvgl_port_unlock();
        }

        return;
    }

    xTaskCreate(
        wifi_connect_task,
        "wifi_connect",
        4096,
        params,
        5,
        NULL);
}

void toggle_password_mode(lv_event_t * e)
{
    (void)e;

    lv_textarea_set_password_mode(
        ui_PasswordTextArea,
        !lv_textarea_get_password_mode(ui_PasswordTextArea)
    );
}