// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ReSpeaker-Dashboard-WiFi

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void scanButton_callback(lv_event_t * e);
void connectButton_callback(lv_event_t * e);
void toggle_password_mode(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
